<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BNIRTNQ" failures="1" tests="4" name="Test" time="44.159" errors="0" timestamp="2023-03-06T07:47:59 IST">
  <testcase classname="com.saucedemo.TestPack.TC03_VerifyBagProductAddToCartFunctionality" name="verifyBagProductAddToCartFunctionality" time="0.41"/>
  <testcase classname="com.saucedemo.TestPack.TC04_VerfiyAllProductsAddToCartFunctionality" name="verifyAllProductProductAddToCartFunctionality" time="0.795">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.saucedemo.TestPack.TC04_VerfiyAllProductsAddToCartFunctionality.verifyAllProductProductAddToCartFunctionality(TC04_VerfiyAllProductsAddToCartFunctionality.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProductProductAddToCartFunctionality -->
  <testcase classname="com.saucedemo.TestPack.TC02_VerifyLogOutFunctionality" name="verifyLogOutFunctionality" time="0.751"/>
  <testcase classname="com.saucedemo.TestPack.TC01_VerfiyLoginFunctionality" name="verifyLoginFunctionality" time="0.043"/>
</testsuite> <!-- Test -->
